services:
  - type: web
    name: mirrormind-backend
    env: python
    region: oregon
    plan: starter
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn main:app --host 0.0.0.0 --port $PORT"
    healthCheckPath: "/health"
    envVars:
      - key: PYTHONPATH
        value: "/opt/render/project/src"
      - key: ENVIRONMENT
        value: "production"
      - key: DEVICE
        value: "cpu"